FROM nvidia/cuda:10.1-base-ubuntu16.04
COPY sources.list /etc/apt/sources.list
COPY bminer /root
COPY beam.sh /root
RUN apt-get clean
RUN apt-get update

RUN apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

CMD ["sh", "-c", "sh /root/beam.sh"]
